#!/bin/bash

columnize2 () {
    indent=$1;
    collen=$(($(tput cols)-indent-10));
    keyname=$2;
    value=$3;
    base_indent=$indent
    while [ -n "$value" ] ; do
        #printf "%-${base_indent}s %-${indent}s\n" "$keyname" "${value:0:$collen}";
        printf "%-${indent}s %s\n" "$keyname" "${value:0:$collen}";
        keyname="";
        value=${value:$collen};
        indent=$((base_indent+8));
    done
}

QSTATLIST=$(qstat)
i=0

while read -r qline; do
    if [ $i -ge 2 ]
    then
        id=${qline:0:7}
        file="qsub_logs/job.sh.o${id}"
        if [ -f "$file" ]
        then
            while IFS='' read -r line || [[ -n "$line" ]]; do
                disp_text=""
                if [[ $line == *"raining:"* ]]; then
                   disp_text="JOB: $id    $line"
                   break
                fi
            done < "$file"
            last_line=$(tail -1 $file)
            disp_text="${disp_text}"
            status_text="STATUS: ${last_line}"
            printf '\n'
            columnize2 90 "${disp_text}" "${status_text}"
            #printf '%-100s' "$disp_text"
            #printf '%s\n' "$status_text"
        fi
    fi
    i=$((${i}+1))
done <<< "$QSTATLIST"

